name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: jackpar/x11-zig:0.16.0-dev.2962

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      run: zig build
